export {
    ensureRoutingListRows,
    applyGraphConnection,
    applyRouteEdgeRemoval,
    buildRouteEdgesFromNodes,
    clearTaskWireReferences,
    collectRoutingReferencedTaskIds,
    isValidPluginConnection,
    listRoutingEndpoints,
    mergeDisplayEdges,
    resolveOutputStubBehavior,
    resolvePluginHandles,
    resolveTaskOutputViews,
    resolveWireTargetHandle,
    terminatesMainSpine,
    type RouteEdgeData,
    type RoutingEndpoint,
    type TaskInputView,
    type TaskOutputView,
} from './pluginWiringRuntime';
